### ISSUE TITLE
Add ‘Services’ and ‘Billing’ to ‘Organization settings’

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#111]
The _Organization settings_ chapter doesn’t currently document the _Services_ and _Billing_ tabs.

**Comment by hilton** [comment]
Two questions for @SilentGert to check during review:
1. Does that bullet list ever show anything other than the number of available licenses and their expiry date?
2. Can there be multiple expiry dates?

**Comment by SilentGert** [comment]
@hilton Just to clarify, only the highest license type is shown. So it is at max one and also just one expiration date.

**Comment by hilton** [comment]
@wolfsoe Ready for translation - #112 is already merged.

**Comment by SilentGert** [comment]
@hilton Wolf has already translated the content and told me to merge it.

**Comment by hilton** [comment]
Ah, okay, thanks. I missed that part.
