### ISSUE TITLE
Fix "broken" search results

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#122]
Currently, the search results are displayed as .rst source text.
This looks weird and text of files referenced by `.. include::` is ignored.

I fixed this for the Signavio docs:
Sphinx allows building txt files with a minimum of markup. I wrote scripts to build the txt files and include them in the html build and to remove (almost) all remaining markup.
A minor tweak in the search template allows fetching the txt files instead of their .rst counterparts.
I'll try to get this fix to work on read the docs.

**Comment by TimKam** [comment]
Fixing this issue adjusting the `build.sh` script works locally, but not on rtd. Let's see if the community can help -> https://github.com/rtfd/readthedocs.org/issues/2276.

**Comment by TimKam** [comment]
Looks like I could make it work on RTD. @wolfsoe let me know if there are any problems with the build on Windows.

**Comment by TimKam** [comment]
@SilentGert: I'll apply this fix to the admin docs as well, if you don't have any objections.

**Comment by SilentGert** [comment]
@TimKam Yep, adding the fix would be appreciated.
