### ISSUE TITLE
Change JavaScript code Snippet in DE manual for issue #124

### ISSUE THREAD

**Issue by wolfsoe** [effektif/user-docs#125]
Change code in manual at [http://docs.workflow.signavio.com/de/latest/action-types.html#javascript-action-script-task](http://docs.workflow.signavio.com/de/latest/action-types.html#javascript-action-script-task) so that startDate variable in WorkflowUI is named "Startdatum" - I do not know what is correct to change as I do not know JavaScript. Code looks like this:

> var requestBody = { "startDate" : startDate };
> 
> request.post( {
>        url: 'http://www.mocky.io/v2/55798e08bdbf280d0d423cb8',
>        body: JSON.stringify(requestBody),
>        headers: { 'Content-Type': 'application/json' }
>  },
>  function (error, response, responseBody) {
>        var log = "HTTP " + response.statusCode + "\n" + responseBody;
>        if (!error && response.statusCode === 200) {
>          console.info(log);
>          var responseData = JSON.parse(responseBody);
>          startDate = responseData.startDate;
>        }
>        else {
>          console.error(log);
>        }
>  }
> );

**Comment by TimKam** [comment]
I'll take this :-)

**Comment by TimKam** [comment]
@wolfsoe Here's the correct German JavaScript Task example: https://workflow.signavio.com/userdocs/process/5771975c62f8a0552c594936/actions/o9g8dj4f5t2ax5jfxy

The variable `startdatum` is German, because it is generated based on the field name (and this should be German, of course).
