### ISSUE TITLE
Admonition support

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#129]
Check all [admonitions](https://github.com/snide/sphinx_rtd_theme/blob/master/demo_docs/source/demo.rst#id63) in both user manual templates and adjust them to our CI if necessary.

**Comment by TimKam** [comment]
To apply the update locally, re-run: `pip install --user -r requirements`.
For me rtd is down atm, so the changes are not yet applied to the production docs.

**Comment by hilton** [comment]
👍 Nice!
