### ISSUE TITLE
Add section: Process Builder / Actions / Changing the action type

### ISSUE THREAD

**Issue by frontendphil** [effektif/user-docs#134]
First off: You don't have to call it "Morphing a task" :)

With the next release, you will be able to change the type of a task. In order to do this, you need to click on the task type icon next to the input field where you can change the name of the task. As this feature increases usability a lot, I would like to have it documented in here :D

**Comment by hilton** [comment]
@TimKam I’m going to commit the docs on a branch for translation, as usual, but the feature isn’t released yet, so you won’t be able to make a German screenshot translation. However, this is the screenshot I’m going to use, so if you comment here with the translations for _Send rejection_ and _candidate rejected_, from the _Hire employee_ example process, then I can make it for you.

![change](https://cloud.githubusercontent.com/assets/232614/16951627/159d3562-4dc6-11e6-92ef-c5ffcc0ae76e.png)

**Comment by hilton** [comment]
… or @wolfsoe - to whom I’ve assigned the pull request, as usual.

**Comment by hilton** [comment]
> The task would be _Absage senden_ the end event. _Kandidat abgelehnt_
