### ISSUE TITLE
Add chapter: Custom system connectors

### ISSUE THREAD

**Issue by SilentGert** [effektif/user-docs#141]
We need to document our new connector framework.
- [x] the new connector admin UI
- [x] the general integration concept
  - how does the workflow communicate with the connector
  - which kind of data can be provided
- [x] the format of the connector descriptor
- [x] the available data types and respective value formats
- [x] the expected URL design of the connector endpoint
- [x] link to the connector examples

**Comment by SilentGert** [comment]
Our example third party system will be a customer database.

Customers
- Text id
- Text fullName
- Email email
- Choice subscriptionType
- Date since
- Number discount

**Comment by hilton** [comment]
@SilentGert I think this is all done, so I’m going to close it. Let me know if there’s still something left to do that I forgot.

**Comment by SilentGert** [comment]
No, I guess we should be good for now.
