### ISSUE TITLE
Table layout clips and scrolls sideways

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#144]
Tables with enough text in are too wide to fit the page column, and get a horizontal scroll bar, instead of wrapping the text in cells.

Also, the pilcrow (¶) link in the table caption should only be shown on hover.

Personally, I’m not a fan of the table styling having background shading _and_ cell borders - one or the other would be enough.

![tables](https://cloud.githubusercontent.com/assets/232614/17296967/ed35a058-5803-11e6-9ff2-15ad77fd2ced.png)

**Comment by hilton** [comment]
I don’t know whether the fix should be CSS in the theme, or whether the markup should be different to use the intended theme styling. I noticed that the table is inside a `div.wy-table-responsive` element.

Also, I make the tables in https://github.com/effektif/user-docs/blob/141-connectors/docs/integration/connectors.rst using [List tables](http://rest-sphinx-memo.readthedocs.io/en/latest/ReST.html#list-tables) which are supposed to support relative column widths, but that didn’t work (and ideally isn’t necessary because auto-width columns are better).

**Comment by hilton** [comment]
While you’re at it, the table cell left/right padding is overly generous, given the limited space; `0.5em` is plenty.

**Comment by TimKam** [comment]
- [x]  Pilcrow (¶) link in the table caption should only be shown on hover
- [x] Smaller table cell left/right padding
- [x] Text wrapping instead of scroll bar in tables
- [x] No horizontal table cell borders (I think the vertical border will look ok)

**Comment by TimKam** [comment]
With these changes, giant tables (with many columns) won't look good, though.
I suppose we shouldn't/won't use giant tables.
