### ISSUE TITLE
Update BPMN import section

### ISSUE THREAD

**Issue by SilentGert** [effektif/user-docs#147]
The section about [BPMN import](http://docs.workflow.signavio.com/en/latest/process-builder.html#bpmn-import) contains the following outdated info:

> Signavio Workflow removes unsupported elements, such as timer events.

Some of the timer events are already supported, maybe we should pick another example.
Furthermore, it could be useful to have a list of supported elements.

**Comment by hilton** [comment]
@SilentGert Does this look complete?

| BPMN element | Signavio Workflow Action type |
| --- | --- |
| Business rule task | DMN Rule Task |
| Call activity | Sub-process |
| End event | End event |
| Exclusive gateway | Exclusive gateway |
| Intermediate timer event | Intermediate timer event |
| Manual task | User task |
| Parallel gateway | Parallel Gateway |
| Script task | JavaScript action (Script task`) |
| Send task (`type=email`) | Send email |
| Service task (`type=changeState`) | Signavio Process Editor state change |
| Service task (`type=boxFileUpload`) | Box Upload file |
| Service task (`type=googleAddCalendarEvent`) | Google Drive - Add calendar event |
| Service task (`type=googleCloudPrint`) | google-print |
| Service task (`type=googleDriveAddRow`) | Google Drive - Add row to sheet |
| Service task (`type=googleDriveFileUpload`) | Google Drive - Upload file |
| Start event | Start event |
| Sub-process (embedded) | Sub-process |
| Swim lanes | Roles |
| Task | User task |
| User task | User task |

**Comment by SilentGert** [comment]
Looks good so far.
