### ISSUE TITLE
Support French

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#162]
We need to adjust the build so it supports French.
I'll do this and merge the branch into `master`.
Afterwards, French will be available as a language option, but the content will still be in English.
Keeping a 'French' branch separate until a minimal set of translations is ready is probably too messy (gettext & merge conflicts).

Any objections @hilton @frontendphil @SilentGert ?

**Comment by hilton** [comment]
C’est bon!

**Comment by TimKam** [comment]
RtD hosts the to-be translated docs at http://docs.workflow.signavio.com/fr/latest/.
