### ISSUE TITLE
Add section: Labels for workflow categorization

### ISSUE THREAD

**Issue by SilentGert** [effektif/user-docs#203]
The next release will contain the new label feature. Labels offer the possibility to categorize and filter workflows on multiple dimensions. 

- Labels can be created, updated, deleted by organization admins in the organizaton settings
- Labels can be assigned to workflows in the editor
  - Assigning a label requires edit access for the workflow
- Labels can be used to filter workflows
  - Selecting two or more labels means a workflows has to be labelled with all of them
- Every organization has the following set of default labels:

![screen shot 2017-03-13 at 15 23 47](https://cloud.githubusercontent.com/assets/187786/23858674/82f9ac30-0801-11e7-9b36-ea5b6b7b2868.png)

It's probably best to add a section in the organization settings chapter for the management of the labels and one in the process builder regarding the assignment. Is there already a chapter for the workflow list which could contain any information regarding the filtering?

**Comment by hilton** [comment]
- [x] _Organization settings_ - add _Labels_
- [x] _Process builder_ - add _Browsing processes_
- [ ] _Process builder_ - add _Filtering the processes list_ (filter by _Labels_, _Owner_, _Trigger_, _More Filters_ - _Published/Unpublished_)
- [x] _Process builder_ - add _Labels_
