### ISSUE TITLE
Wrong links in examples chapter

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#210]
In the examples chapter we have links like `http://www.effektif.com/news/email-notification-workflow-patterns/#section-2` and `http://www.effektif.com/news/document-workflow-patterns/#section-1` that are technically not dead, but redirect to a too generic page.

1) We should fix them.
2) We might want to make the "broken link" check fail if a link is redirected. Do you think this is a good idea, @hilton ?

**Comment by hilton** [comment]
> We might want to make the "broken link" check fail if a link is redirected. Do you think this is a good idea, @hilton ?

Yes.

**Comment by hilton** [comment]
Where are these, exactly? I can't find any links to `effektif.com`, and `approve-expense-claim.rst` contains these two links:

```rst
`Document Approval <http://www.signavio.com/post/document-workflow-patterns/>`_
`Result Notification <http://www.signavio.com/post/email-notification-workflow-patterns/>`_
```

**Comment by TimKam** [comment]
https://raw.githubusercontent.com/effektif/user-docs/master/docs/include_examples/approve-expense-claim.rst

**Comment by hilton** [comment]
Ah, looks like a merge error from `166-connectors-german`. I’ll submit a new PR to revert the links to `signavio.com`

**Comment by TimKam** [comment]
Thanks.
