### ISSUE TITLE
Add single option endpoint to connectors

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#212]
https://github.com/effektif/product/issues/3812 is a bug caused by the Signavio Workflow back-end being unable to resolve the name for a single option, in the case where the `/:type/options` endpoint doesn't return all options.

Add a new `/:type/options/:id` endpoint that returns a single element of the `/:type/options` response.

**Comment by TimKam** [comment]
I suppose I take over now for the German translation

**Comment by hilton** [comment]
@TimKam I thought you weren't translating the connector's chapter.

**Comment by TimKam** [comment]
Dominik translated it recently.
