### ISSUE TITLE
Remove ‘Example processes’ chapter

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#232]
Now that the user guide’s [Example processes](http://docs.workflow.signavio.com/en/latest/examples.html) are published on www.signavio.com at _Resources & Services > Knowledge Center > [Workflow Examples](https://www.signavio.com/workflow-examples/)_ we no longer need them in the user guide.

However, before removing the user guide chapter, I figure the German translations should move to the web site. @TimKam Is that something you can do?

**Comment by TimKam** [comment]
Yes, I can move them there. We should also add a redirect (static html file).

**Comment by hilton** [comment]
A redirect sounds good. I was also thinking about adding a small _Example processes_ section to the _Processes_ chapter, with a couple of sentences that link to https://www.signavio.com/workflow-examples/

**Comment by TimKam** [comment]
I removed the chapter and added a redirect page. I leave this ticket open in case you want to add a small section that explicitly points to the website.

**Comment by hilton** [comment]
Yes, I’ll add that to the _Introduction_ I think, so we can have some concrete examples before we start talking about abstractions like _process_, _case_ and _task_.
