### ISSUE TITLE
Translate new workflow examples to German

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#242]
Last week and today I published some new ‘workflow examples’:

* [x] [Arrange business trip](https://www.signavio.com/workflow-examples/arrange-business-trip/)
* [x] [Know Your Customer](https://www.signavio.com/workflow-examples/know-your-customer/)
* [x] [Approve Meeting Minutes](https://www.signavio.com/workflow-examples/approve-meeting-minutes/)
* [x] [Onboard new employee](https://www.signavio.com/workflow-examples/onboard-new-employee/)
* [x] [Publish blog post](https://www.signavio.com/workflow-examples/publish-blog-post/)

In Wordpress, you can browse these via [pages published in May](https://www.signavio.com/wp-admin/edit.php?s&post_status=all&post_type=page&action=-1&m=201705&lang=en&seo_filter&filter_action=Filter&paged=1&action2=-1).

Please add German translations to the web site. Timmi knows how to do this in Wordpress, because he did the other German translations.

Note that we should probably do this instead of Marketing, even though it’s on the web site, because nature of the content is more like product documentation, so it’s probably harder for them to translate.

**Comment by Lengocduong** [comment]
We also need to translate these articles:

- https://www.signavio.com/post/email-notification-workflow-patterns/#
- https://www.signavio.com/post/approval-workflow-modelling-patterns/
- https://www.signavio.com/post/collaboration-workflow-patterns/#

Meanwhile, I will link to the English version (?)

**Comment by Lengocduong** [comment]
Please ignore my previous comment. Timmi told me that our Workflow blog is English-only, so that links are ok.
