### ISSUE TITLE
New activity: Create Document from Word template

### ISSUE THREAD

**Issue by steffektif** [effektif/user-docs#269]
### Modelling-time
Workflow Accelerator has a brand new activity which allows modellers to upload a Word document. 
Once this template is uploaded SWAG'ccelerator 'scans' the template file for placeholders (Microsoft calls them `Content Controls`) and creates a form from the foundings of the scan. 

The user can fill this form with variables or static text. This works exactly like the sub-process-activity. So you need to define an output as well. This output can be used like every other variable in the workflow.

Like in this picture:
![documenttemplateactivity](https://user-images.githubusercontent.com/5119185/27904344-bac085ae-623c-11e7-9026-e3c907ba4deb.png) 

### Run-time
Once a case is created and the workflow approaches the new Document Template activity  the template is loaded and the placeholders get 'populated' with the workflow values. In this way a new document is created.

### How to add content controls to Word

First some important things:
**1. Adding content controls requires to show the developer ribbon in Word -> [follow this guide](https://msdn.microsoft.com/en-us/library/bb608625.aspx)**
**2. Thanks to Microsoft this is only possible in Windows. The Mac version of Word simply does not support adding content controls yet. (You can still see them on Macs version of Mac)**
**3. For the first version of this feature only text content controls (plain and rich text) are supported, all others just won't show up after the scan happened.**

So here is what the user needs to do, to make content controls work with Workflow Accelerator:
1. Open a document or create a new one
2. Write some text
3. Click the `Developer` ribbon / tab (black arrow in screenshot)
4. Click the rich or plain text button (red arrow/ box in screenshot)
5. Click the Properties button (blue arrow in screenshot)
![developerstab](https://user-images.githubusercontent.com/5119185/27905508-71a51520-6240-11e7-9b3d-d955737b4da0.png)
6. Enter a title 
![propertiesdialog](https://user-images.githubusercontent.com/5119185/27905597-ab5706c0-6240-11e7-9845-b259bfcda881.png)
7. (Optional) Enter a default value (recommended) 
From this:
![addedcc](https://user-images.githubusercontent.com/5119185/27905624-c96b4b94-6240-11e7-8d59-0af31ef69bc4.png)
To that: 
![defaultvaluecc](https://user-images.githubusercontent.com/5119185/27905625-cb0cffb0-6240-11e7-8a42-e79cbd4b993b.png)
8. Repeat :)

That's it.

Entering a default value will lead to using that value over `Click or tap here to enter text.`. Which we can not prevent from happening if you keep a field empty.

### Restrictions

As mentioned earlier there are some restrictions, since this is the first version of the feature. 
1. Only rich and plain text content controls are supported for now (Others don't show up)
2. Leaving fields empty will use the value set in the Word document, if this one is blank as well, Word will set `Click or tap here to enter text.` in the users language (Word-wise).
3. Adding content controls is a Windows-only thing.

**Note: This is not merged yet, it's not available on CI neither on production yet.**

**Comment by SilentGert** [comment]
@steffektif This works with Word 2010+, right?

**Comment by steffektif** [comment]
Some say it has been introduced 2007 already. On [this site](http://gregmaxey.com/word_tip_pages/content_controls.html) you can find an overview of content controls and when they have been introduced.

**Comment by steffektif** [comment]
I would guess, that our best shot is to set requirements to 2013

**Comment by steffektif** [comment]
Added this file for testing: 
[extendedControls.docx](https://github.com/effektif/user-docs/files/1127699/extendedControls.docx)

**Comment by steffektif** [comment]
[templateTest.docx](https://github.com/effektif/user-docs/files/1138702/templateTest.docx)

**Comment by SilentGert** [comment]
@Lengocduong @TimKam Is it possible that we extend the explanations a bit on how to create content controls or link to a better resource for that? There are already support requests coming of customers being confused on how to get fields in there and how to name them.

**Comment by Lengocduong** [comment]
If we can use other than Microsoft-origin documentation, this could be an option: 
https://nikpatel.net/2010/04/11/add-content-controls-in-the-word-documents-for-the-open-xml-automation/ ? @TimKam what do you think?

**Comment by TimKam** [comment]
Perhaps there *is* actually a better official resource. Like this one: https://support.office.com/en-us/article/Create-forms-that-users-complete-or-print-in-Word-040c5cc1-e309-445b-94ac-542f732c8c8b
What do you think @SilentGert ?

**Comment by SilentGert** [comment]
I'm pro official documentation, although I like that the other one has more screenshots. 

Can you additionally cover in one or two sentences that within the properties of a content control you can set `Title` which is the name that will also be shown in our mapping dialog. How to access the properties dialog in Word is mentioned in the official documentation.
