### ISSUE TITLE
Add section: licenses/versions

### ISSUE THREAD

**Issue by frontendphil** [effektif/user-docs#28]
I feel like we need to explain the different version somehow. Also it would be good to have a link with a description ready to send out. Especially for people who want to register / activate their academic version.

**Comment by hilton** [comment]
Sounds like a good idea. Do you mean an overview of the different features in the different versions? If so, that’s something I’m going to have to look into first, especially for the _Enterprise Cloud_ features:

> - Add your own connectors
> - LDAP connectivity / SSO
> - Analytics
> - Escalation management

**Comment by hilton** [comment]
_How to buy_, and #97 - the section about how to set-up an academic license, sound like sections in the _Introduction_ chapter.

**Comment by hilton** [comment]
@frontendphil It seems that I haven’t been able to resolve this issue because I don’t know what to include. Would it be possible to suggest some bullets or chat/Skype about what I need to say about the different versions and licenses?

**Comment by hilton** [comment]
Christian explained a bit. I didn’t release that it was actually possible to set-up a developer cloud license.

For developer cloud, document:
- option to downgrade on `/{orgkey}/buy` page when license has expired
- same features as professional
- single user
- no cloud connectors
- no collaboration

**Comment by hilton** [comment]
@SilentGert Please could you review the [new licenses chapter](https://github.com/effektif/user-docs/blob/9ec3163a47e6d846dab3a5bbad4b47486e46d8a3/docs/licenses.rst) to check that the information is correct. If so, please assign to @wolfsoe for translation.
