### ISSUE TITLE
Adjust document template user-docs

### ISSUE THREAD

**Issue by steffektif** [effektif/user-docs#281]
As we encountered a bug that was found by a customer. We recognized that rich text fields do not support line breaks. That seems to be no problem, but we should document that. For this, it would be nice to have that hint that explains that only plain text fields with the option 'Allow carriage returns (multiple paragraphs)'  are capable of using line breaks. 

Option look like this:
<img width="327" alt="screen shot 2017-07-24 at 08 05 06" src="https://user-images.githubusercontent.com/5119185/28510137-dd4917a4-7046-11e7-8e63-d8bfe0039fe1.png">

**Comment by TimKam** [comment]
@Lengocduong We probably don't need to provide screenshots, but we need to find out what the check box is called in German. Can you ask Support if any of them has a German installation of MS Office and check?

**Comment by Lengocduong** [comment]
"Wagenrückläufe zulassen (mehrere Absätze)"
- sounds strange!

![bildschirmfoto 2017-07-25 um 16 25 38](https://user-images.githubusercontent.com/26876106/28577112-23b04d4c-7156-11e7-81ae-8dba0d1b8c78.png)
