### ISSUE TITLE
Limit the number of users who can create new workflows

### ISSUE THREAD

**Issue by SilentGert** [effektif/user-docs#285]
As an admin in my organization settings I can activate a restriction who is able to create new processes. I can select an existing group to be the modeller group. Only users of that group can:
- create new processes
- copy processes
- import processes

The normal process access stays untouched from that feature. If a user is not part of the modelling group, but has edit rights for an existing process, he can change this process. But he cannot create a new one.

As a side note, the transfer of processes between Process Manager and Workflow Accelerator is not affected by this limitation. Any modeller can transfer a process from within Process Manager to Workflow Accelerator.

**Comment by hilton** [comment]
For what it’s worth, from a documentation point of view, the UI seems more complex than necessary. It would be enough to have a single group selector that defaults to the whole organisation. Precedent for this is that you can select the whole organisation when you select process access control.

**Comment by SilentGert** [comment]
Which is from an implementation perspective not an existing group. But yeah that could be a different kind of visualization.
