### ISSUE TITLE
Add chapter: Process examples

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#36]
Add a chapter to document the example processes, based on the documents in the [Examples backlog](https://docs.google.com/document/d/1gWI4wRXDNbImNMalOW6zDyEgPhpKNarw4sNz36Whlzk/).

**Comment by hilton** [comment]
@frontendphil Should we talk about this before I go ahead? I have 15 examples to start with, with a total of 4500 words in my current drafts. I’d like to edit this to make the first version next week, to make them consistent with each other and to make them shorter. I can make a pull request after that.

**Comment by frontendphil** [comment]
@hilton Regarding process examples it might also make sense (if you haven't done this already) to get in touch with sales on that matter. I got the feedback, that generalised examples are nice but industry specific ones are even better. I don't know how your current drafts look like, but we might do one or two examples per industry (if that's possible).

**Comment by hilton** [comment]
See [Examples backlog](https://docs.google.com/document/d/1gWI4wRXDNbImNMalOW6zDyEgPhpKNarw4sNz36Whlzk/). I agree that industry-specific ones are more interesting and useful, but they're also to harder to write when you're just making it up, in the absence of implementation project experience in that industry.

Adding them to the user guide is actually a first step in preparing the content for https://signavio.plan.io/issues/6772 - adding them as _Process templates_ to _www.effektif.com_

**Comment by frontendphil** [comment]
Nice document. Again, wdyt I go over this list with the sales guys and figure out, if they have some more insights or maybe know the pain points in the respective processes?

**Comment by hilton** [comment]
Please do. So far I’ve been entirely unsuccessful at getting them to engage with any of the marketing material I’ve written. As far as I can tell, none of them have even read any of it.

**Comment by hilton** [comment]
Please note that whether or note the sales team respond to this in the short term, this chapter is initially for marketing. Specifically, it’s the content for new Effektif web pages that Diana is working on.
