### ISSUE TITLE
ToC incomplete on small screens

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#67]
When the currently expanded ToC is very long, it will be cut off on small screens.

Should we make it scroll-able for such cases?

**Comment by hilton** [comment]
Yes, good plan. I had a quick look, and it isn’t obvious why it doesn't scroll on http://docs.effektif.com, given that it does when I build it locally.

**Comment by hilton** [comment]
I’ve enabled scrolling in the sidebar.
