### ISSUE TITLE
Portrait mode display: improve navigation

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#68]
The top menu bar of the "mobile" layout is not fixed to the screen.

Thus, navigation is quite cumbersome when scanning longer chapters.

Should we have the menu bar fixed?

Or rather appear when the user scrolls up?

**Comment by hilton** [comment]
Personally, I prefer it how it is, so that you don't lose any of the (small) screen space when reading on a phone.

**Comment by TimKam** [comment]
Ok, I don't have a strong opinion on this. Let's leave it as it is, then.

**Comment by hilton** [comment]
Agreed. We should come back to this kind of thing if we hear about users reading the docs on mobile.
