### ISSUE TITLE
Fix version numbers

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#71]
The published docs have a number of version, for 2.x releases, but it isn't clear what the plan there is. Do we need the versions other than _latest_ - perhaps for on-premise releases?

**Comment by hilton** [comment]
The fix is to just remove the version number navigation, since we don't need it.

**Comment by hilton** [comment]
It sounds like there's an admin interface for versions, which suggests that the fix is to deselect versions there:

> Look on the “Versions” page of your project’s admin […] On the Versions page you can tell us which versions you’d like us to build docs for

**Comment by frontendphil** [comment]
Done.
