### ISSUE TITLE
JavaScript action: document available libraries

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#95]
According to Christian, the available libraries are:

> - `request` https://www.npmjs.com/package/request
> - `_` https://www.npmjs.com/package/lodash
> - and you can use console for log output
> - and in general the vanilla JS API which is available in Node.js

**Comment by SilentGert** [comment]
Instead of _vanilla JS API_ rather use _plain JS API_. There seems to be a npm module called vanilla JS.
