### ISSUE TITLE
Add chapter: Academic edition

### ISSUE THREAD

**Issue by frontendphil** [effektif/user-docs#97]
This chapter should highlight how one can activate the academic edition and what are the requirements you need to meet (i.e. academic email address)

**Comment by hilton** [comment]
Academic license instructions:
- How to qualify for an academic license (research/education purposes only not uni admin, be a student with a uni email address)
- How to activate academic license (org settings, billing tab, activate for one year)

**Comment by hilton** [comment]
Fixed by #28.
